// my-vue/src/views/orders/Orders.vue
<template>
  <div>
    <el-pagination
            background
            layout="prev, pager, next"
            @current-change="clickChange"
            :total="tableData.total_count">
    </el-pagination>
    <el-table
            ref="multipleTable"
            :data="tableData.data"
            tooltip-effect="dark"
            style="width: 100%"
            @selection-change="handleSelectionChange">
      <el-table-column
              type="selection"
              width="55">
      </el-table-column>
      <el-table-column
              prop="order_number"
              label="订单号"
              width="220">
      </el-table-column>
      <el-table-column
              prop="date_placed"
              label="下单时间"
              width="100">
      </el-table-column>
      <el-table-column
              prop="total_amount"
              label="数量"
              width="50">
      </el-table-column>
      <el-table-column
              label="购买途径"
              width="80">
        <template scope="scope">
          官网
        </template>
      </el-table-column>
      <el-table-column
              prop="product_shipping_address.name"
              label="姓名"
              width="120">
      </el-table-column>
      <el-table-column
              prop="product_shipping_address.mobile"
              label="电话"
              width="120">
      </el-table-column>
      <el-table-column
              prop="product_shipping_address.address"
              label="收货地址"
              width="200">
      </el-table-column>
      <el-table-column
              prop="product_shipping_address.address"
              label="支付状态"
              width="100">
        <template scope="scope">
          已支付
        </template>
      </el-table-column>
      <el-table-column
              label="操作">
        <template slot-scope="scope">
          <el-button type="primary" @click="itemDetails(scope.$index, scope.row)">详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <!--详情modal-->
    <el-dialog title="收货地址" :visible.sync="dialogTableVisible">
      <el-table :data="gridData">
        <el-table-column property="date" label="日期" width="150"></el-table-column>
        <el-table-column property="name" label="姓名" width="200"></el-table-column>
        <el-table-column property="address" label="地址"></el-table-column>
      </el-table>
    </el-dialog>
  </div>
</template>

<script>
  export default {
    name: "Orders",
    data(){
      return {
        multipleSelection: [],
        gridData: [{
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }],
        dialogTableVisible: false
      }
    },
    computed: {
      tableData(){
        return this.$store.state.orderModule.orders
      }
    },
    created(){
      //触发一个事件
      let params = {
        page: 1,
        limit: 10,
        order_number: '',
        sort_by: 'order_date',
        keyword: '',
        order_status: '',
        shipping_status: '',
        paymethod: '',
        channel: '',
        month: ''
      };
      this.$store.dispatch('getAllOrdersApi', {params: params});
    },
    methods: {
      handleSelectionChange(val) {
        this.multipleSelection = val;
      },
      //翻页
      clickChange(e){
        let curr_page = e;
        let params = {
          page: curr_page,
          limit: 10,
          order_number: '',
          sort_by: 'order_date',
          keyword: '',
          order_status: '',
          shipping_status: '',
          paymethod: '',
          channel: '',
          month: ''
        };
        this.$store.dispatch('getAllOrdersApi', {params: params});
      },
      //查看详情
      itemDetails(index, row){
        console.log(index, row);
        const item_index = index; //该行角标
        const row_data = row; //该行数据
        this.dialogTableVisible = true
      }
    }
  }
</script>

<style scoped>

</style>

// my-react/src/containers/orders/Orders.js
import React, {Component} from 'react';
import {connect} from "react-redux";
import { Table, Button } from 'antd';
import { getAllOrders } from '../../redux/actions/allOrdersActions';
import './orders.css';

const columns = [{
  title: '订单号',
  key: 'orderNum',
  dataIndex: 'order_number',
  render: text => <div>{text}</div>,
}, {
  title: '下单时间',
  key: 'time',
  dataIndex: 'date_placed',
  render : text => <div>{text}</div>
}, {
  title: '数量',
  key: 'num',
  dataIndex: 'total_amount',
  render : text => <div>{text}</div>
}, {
  title: '购买途径',
  key: 'buyWay',
  render: () => <div>官网</div>,
},{
  title: '姓名',
  key: 'name',
  dataIndex: 'product_shipping_address',
  render: (data) => <div>{data.name}</div>,
},{
  title: '电话',
  key: 'tel',
  dataIndex: 'product_shipping_address',
  render: (data) => <div>{data.mobile}</div>
},{
  title: '收货地址',
  key: 'address',
  dataIndex: 'product_shipping_address',
  width: 120,
  render: (data) => <div>{data.address}</div>
},{
  title: '支付状态',
  key: 'payStatus',
  render: () => <div>已支付</div>
},{
  title: '发货状态',
  key: 'faStatus',
  render: () => <div>未发货</div>
},{
  title: '后续状态',
  key: 'houStatus',
  render: () => <div>待发货</div>
},{
  title: '运单号',
  key: 'yunNum',
  render: () => <div>运单号</div>
},{
  title: '操作',
  key: 'action',
  render: () => <div>编辑、详情</div>
}
];

class Orders extends Component {
  constructor(props) {
    super(props);
    this.state = {}
  }

  componentDidMount(){
    console.log('9999999')
    let param = {
      page: 1,
      limit: 10,
      order_number: '',
      sort_by: 'order_date',
      keyword: '',
      order_status: '',
      shipping_status: '',
      paymethod: '',
      channel: '',
      month: ''
    };
    this.props.dispatch(getAllOrders(param))
  }

  render() {
    const {allOrders, hasOrders, table_config} = this.props.allOrders;
    console.log(table_config,'pagination')
    return (
      <div className="orders-container">
        <div>
          <Button type="primary">未发货</Button>
          <Button>已发货</Button>
          <Button>全部订单</Button>
          <Button>添加订单</Button>
        </div>
        <Table {...table_config} rowKey={record => record.order_id} columns={columns} dataSource={hasOrders ? allOrders.data : null} />
      </div>
    )
  }
}

export default connect((state) => {
  console.log(state,'推荐');
  return {
    allOrders: state.allOrdersReducers
  }
})(Orders)
